### ISSUE TITLE
Many datasets with platform type raster don't have numberbands yet CIP says this field is mandatory

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#10]
We can make these records valid by using gco:nilReason='unknown' but is this what is wanted. Many of these records have bandList set, perhaps the number of bands can be inferred from this field? Guidance required on both whether the numberbands field is indeed mandatory and/or what to do when it has a null value.

**Comment by spatialgeorge** [comment]
- Band list are not all populated - some records will remain unknown
- Field and will remain mandatory in Geonetwork
