### ISSUE TITLE
Project Location field

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#12]
Presumably this is a geographic description of where the project took place. But is this a controlled vocabulary (not in the rastermeta tables) and if so where does it come from? Should be a thesaurus most likely. If thesaurus then it could be mapped as a keyword with type 'place' and a reference to the thesaurus, if it is an uncontrolled text description then identificationInfo/extent/geographicDescription.

**Comment by spatialgeorge** [comment]
- Simon to implement into the geographic extent field.
- Free text field.

**Comment by sppigot** [comment]
Mapped.
