### ISSUE TITLE
Problems with contacts

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#18]
Individuals 135, 200, 304, 387, 389, 445, 578 (from the individual table) cause NPE during mapping. Probably no organisation id related to the contact.

**Comment by mickconroy** [comment]
Yes these contacts were often duplicates. 200 & 389 have no ID. The others have an organisation id but it has obviously been deleted at some stage. I have made some edits to these contacts and will wait a few days to see if they get replicated in SDE.
