### ISSUE TITLE
Projects: acquisitionInformation//operation//status/MD_ProgressCode 

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#2]
No indication of whether the acquisition operation for the rastermeta project is complete (could be done on the acquisitionYear but this is not precise enough). So have decided that if the project availability is anything other than Unknown, then the acquisition operation is complete and the codelist value is set to 'completed', otherwise codelist value is 'underDevelopment'.

**Comment by sppigot** [comment]
This is a required field so we need a value - could set to gco:nilReason='inapplicable' but we should try and do better as others may be looking at this field for some idea of when or whether the acquisition is complete?

**Comment by sppigot** [comment]
This issue also applies to datasets ie. sources and footprints

**Comment by spatialgeorge** [comment]
Complete

**Comment by sppigot** [comment]
Implemented: all projects and datasets will have acquisition status set to complete
