### ISSUE TITLE
Duplicate records errors in DELWP raster meta database

### ISSUE THREAD

**Issue by milleri** [geonetwork-delwp/rastermeta#25]
I have deployed rastermeta in the DELWP environment, configured against their prod rastermeta Oracle database.  When I run it it worked for contacts but failed for projects and datasets - on both cases with a "more than one row with given identifier exists" error.

For datasets, this was in FileXMLWriter line 156 and referenced the au.gov.vic.delwp.DEM entity, id 17220.  For projects it was line 108 and the Individual entity, id 802.

Presumably this reflects differences in the test database you have been working with compared to the current state of the prod database.  What is the best way to resolve this - do you want a resupply of the current prod database?  or are you able to change the Hibernate mappings to reflect this situation?

**Comment by sppigot** [comment]
@milleri I think this is #13 - it is actually invalid in the database. I worked around it by just arbitrarily and manually dropping one of the demdetails for each dataset that had two. (See the description of #13 for more details). I think there was a commitment to fix this in the production database but maybe this hasn't been possible yet.

**Comment by sppigot** [comment]
The above comment refers to the DEM issues on datasets. I'll get back on the project issue shortly.

**Comment by milleri** [comment]
@sppigot Ok thanks - I hadn't looked at #13.  I'll provide the duplicate DEM details to DELWP and see if they can fix the problem at source.
