### ISSUE TITLE
Generate UUID mapping file

### ISSUE THREAD

**Issue by milleri** [geonetwork-delwp/rastermeta#27]
To support the generation of footprints, we need a CSV file to be created which lists the projectid from raster meta and the related UUID value generated.
For raster datasets, we also need a list of their ANZLICID and the related UUID.  Not sure where the ANZLICID is stored in the raster meta tables - if its not obvious, Ross can provide this information.

**Comment by sppigot** [comment]
This can be obtained from geonetwork catalogue using utils/pyscripts/getdatabaseids.py
rastermeta and metashare tools write anzlicid to dataIdentification/citation/identifier - this gets indexed as databaseid, rastermeta tool (latest commit) also writes projectid to databaseid so the python script writes out a complete comma separated list of uuid, databaseid for all records in the catalogue.
