### ISSUE TITLE
Invalid rastermeta projects

### ISSUE THREAD

**Issue by milleri** [geonetwork-delwp/rastermeta#32]
When rastermeta is run in the DELWP environment, approx 1000 projects are failing validation and being written to the invalid directory.  Still look ok and GeoNetwork harvests them ok - not sure what needs to happen to fix this - it's not critical.

Example of error given is:

2020-07-17T15:19:39,829 INFO  [main] - Processing Project '2009-10 Victorian State Wide Rivers LiDAR Project - Port Phillip and Westernport CMA' with ID 14152 uuid 4b647f5c-0e94-5b3a-a550-919751f9980e
2020-07-17T15:19:40,228 ERROR [main] - Validation of '4b647f5c-0e94-5b3a-a550-919751f9980e' against http://schemas.isotc211.org/19115/-3/mdb/2.0 FAILED:
2020-07-17T15:19:40,228 ERROR [main] - 
XSD Validation error(s):
<xsderrors>
  <error>
    <typeOfError>ERROR</typeOfError>
    <errorNumber>1</errorNumber>
    <message>cvc-complex-type.2.4.a: Invalid content was found starting with element 'cit:identifier'. One of '{"http://standards.iso.org/iso/19115/-3/cit/2.0":citedResponsibleParty, "http://standards.iso.org/iso/19115/-3/cit/2.0":presentationForm, "http://standards.iso.org/iso/19115/-3/cit/2.0":series, "http://standards.iso.org/iso/19115/-3/cit/2.0":otherCitationDetails, "http://standards.iso.org/iso/19115/-3/cit/2.0":ISBN, "http://standards.iso.org/iso/19115/-3/cit/2.0":ISSN, "http://standards.iso.org/iso/19115/-3/cit/2.0":onlineResource, "http://standards.iso.org/iso/19115/-3/cit/2.0":graphic}' is expected. (Element: cit:identifier with parent element: cit:CI_Citation)</message>
    <xpath>mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:identifier</xpath>
  </error>
</xsderrors>

**Comment by sppigot** [comment]
Yeah it's the operation citation block inside the acquisitionInfo. The standard wants one of the listed fields in the complaint but rastermeta doesn't have any info we want to put in there. It's not critical and GeoNetwork doesn't care and it's unlikely to cause any issues for consumers.
