### ISSUE TITLE
duplication of RasterID in AerialPhotoDetails table in RASTERAPP schema

### ISSUE THREAD

**Issue by tp0b** [geonetwork-delwp/rastermeta#33]
Raster dataset harvesting stops due to duplicates of RasterID (i.e. 66880) in AerialPhotoDetails table; thus no raster dataset is shown in geonetwork. Issue was passed to CIP team to remove duplicate. 

Response from CIP sometime can be slow and Datashare is not providing raster order function at the moment, Alena Moision from CIP proposes

"So just to confirm, it does a full and complete refresh each time - not just picking up changes? 

Will this process be continuing until the editing capability for Geonetwork is released? If so, it could be more efficient to drop these regular refreshes, go with what you have already harvested, and do a final pull right before we are ready to deprecate Rastermeta" @sppigot  and @milleri  how easily this option can be done?

**Comment by svdeveloper1** [comment]
You can easily suspend the harvesting of metadata from raster meta, leaving the raster metadata in Geonetwork unchanging.  Clearly if there is a current problem which has impacted the raster metadata records, this would need to be corrected and a proper harvest completed before you suspended the harvesting.

Suspending harvesting involves 2 steps:
1. Disable the Geonetwork harvesting jobs via the Geonetwork web console.  There are three to be disabled, raster meta contacts, datasets and projects
2. If desired, disable the raster metar process from running nightly.  This step is not critical (ie it could be left to run and fail, but via step 1 have GeoNetwork ignore its results).  If you refer to disable it, the related cron job on the metar server would need to be removed/disabled.

**Comment by tp0b** [comment]
> You can easily suspend the harvesting of metadata from raster meta, leaving the raster metadata in Geonetwork unchanging. Clearly if there is a current problem which has impacted the raster metadata records, this would need to be corrected and a proper harvest completed before you suspended the harvesting.
> 
> Suspending harvesting involves 2 steps:
> 
> 1. Disable the Geonetwork harvesting jobs via the Geonetwork web console.  There are three to be disabled, raster meta contacts, datasets and projects
> 2. If desired, disable the raster metar process from running nightly.  This step is not critical (ie it could be left to run and fail, but via step 1 have GeoNetwork ignore its results).  If you refer to disable it, the related cron job on the metar server would need to be removed/disabled.

Thank you Tom. For step 1, do you mean I click on Disable tab for RasterMetaContact, RastermetaDataset, and RastermetaProject as in the screenshot below?
![image](https://user-images.githubusercontent.com/64397239/95544494-f9cecc00-0a46-11eb-96f5-f16f6aa3d620.png)

For step 2, i can see run_rastermeta_metar.sh in the folder /var/geonetwork/metar/metadata/rastermeta#. Do you mean i should disable this job run_rastermeta_metar.sh. If so, how can I do it? I can not see it in the crontab job list.

**Comment by svdeveloper1** [comment]
For 1, yes click on the disable button.
For 2, this job is on the metar server, not the Geonetwork server.  Log in to the metar server as the metar user and you'll see the jobs in cron.
