### ISSUE TITLE
Project record 

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/rastermeta#39]
All Project related records are missing the metadata constraints
![image](https://user-images.githubusercontent.com/46309965/144938945-c88c45f6-162f-4cee-8b19-a38cf3f40419.png)

Also while editing a project, clicking on the associated record, opens a new window with unusual formatting.
![image](https://user-images.githubusercontent.com/46309965/144939228-82b18298-6542-44fe-90a5-89a6a1082c6d.png)

**Comment by sppigot** [comment]
Fixed in delwp-gn

**Comment by sppigot** [comment]
Be aware that this could lead to confusion as the view will have buttons at the top that the user can use to edit etc and the view opens in a new tab.
