### ISSUE TITLE
Lidardetails table: missing lookups for ellipsoidformat, ellipsoidverticaldatum and geoidverticaldatum

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#4]
These lookup tables (usually prefaced with RT_<name>) don't seem to be present in the database dumps of rastermeta that I have received. All fields have an integer id in the database.

**Comment by sppigot** [comment]
Question about mandatory: Rastermeta interface shows them as mandatory(?) but database has nulls or 0 or ? - should they not be conditional on the ellipsoidProvided field (boolean)?

**Comment by spatialgeorge** [comment]
- These remain elipsoidverticicledatamun as mandatory
- Elippsoidvertical & geoidvertcaldatumn made conditional

- Michael to investigate further

**Comment by mickconroy** [comment]
Simon refer to RASTERAPP.RT_VERTICALMODEL

**Comment by mickconroy** [comment]
For Ellipsoidformat refer to RASTERAPP.RT_DATASETFORMAT

**Comment by sppigot** [comment]
RT_VERTICALMODEL should give me geoidverticaldatum and ellipdsoidverticaldatum.
ellipsoidformat maps to RASTERAPP.RT_DATASETFORMAT?

**Comment by sppigot** [comment]
RT_VERTICALMODEL implemented for geoidverticaldatum and ellipsoidverticaldatum. Await confirmation that datasetformat is the correct rt table for the ellipsoidformat - thanks Michael.

**Comment by mickconroy** [comment]
Yes the datasetformat is the correct mapping for elliposidformat.  This is just a data format table.

**Comment by sppigot** [comment]
Thanks Mick will plug that in shortly.
