### ISSUE TITLE
Citations: When using something that DELWP is responsible for, the citation should have a citedResponsibleParty with the default delwp organisation contact in it.

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#5]
Definitely useful to use an xlink here or just adopt a policy that wherever the citation is left blank, delwp is assumed to be the owner of the code used.

**Comment by sppigot** [comment]
This applies to both rastermeta and metashare tools.

**Comment by spatialgeorge** [comment]
- Noted

**Comment by spatialgeorge** [comment]
Noted

**Comment by sppigot** [comment]
Leave blank: delwp is assumed to be the cited responsible party.
