### ISSUE TITLE
Settings the status of the acquisition of the imagery for projects & mosaic and source datasets

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/rastermeta#7]
At present using the Availability: if Availabilityid in table datasetdetails is anything other than 'Unknown' then the status of the acquisition of the imagery data is considered 'complete'. Otherwise the status of the acquisition is not set (ie. gco:nilReason='unknown'). The xpath of this elements is /MD_Metadata/acquisitionInfo/MI_AcquisitionInformation/operation/MI_Operation/status (it is a mandatory field in the -3 standard)

**Comment by spatialgeorge** [comment]
- Set availability to compete
